packages:
  - .
  - ui
  - packages/*
  - extensions/*

onlyBuiltDependencies:
  - "@whiskeysockets/baileys"
  - "@lancedb/lancedb"
  - "@lydell/node-pty"
  - "@matrix-org/matrix-sdk-crypto-nodejs"
  - authenticate-pam
  - esbuild
  - protobufjs
  - sharp
  - "@napi-rs/canvas"
