export const browserCoreExamples = [
  "clawdbrain browser status",
  "clawdbrain browser start",
  "clawdbrain browser stop",
  "clawdbrain browser tabs",
  "clawdbrain browser open https://example.com",
  "clawdbrain browser focus abcd1234",
  "clawdbrain browser close abcd1234",
  "clawdbrain browser screenshot",
  "clawdbrain browser screenshot --full-page",
  "clawdbrain browser screenshot --ref 12",
  "clawdbrain browser snapshot",
  "clawdbrain browser snapshot --format aria --limit 200",
  "clawdbrain browser snapshot --efficient",
  "clawdbrain browser snapshot --labels",
];

export const browserActionExamples = [
  "clawdbrain browser navigate https://example.com",
  "clawdbrain browser resize 1280 720",
  "clawdbrain browser click 12 --double",
  'clawdbrain browser type 23 "hello" --submit',
  "clawdbrain browser press Enter",
  "clawdbrain browser hover 44",
  "clawdbrain browser drag 10 11",
  "clawdbrain browser select 9 OptionA OptionB",
  "clawdbrain browser upload /tmp/file.pdf",
  'clawdbrain browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "clawdbrain browser dialog --accept",
  'clawdbrain browser wait --text "Done"',
  "clawdbrain browser evaluate --fn '(el) => el.textContent' --ref 7",
  "clawdbrain browser console --level error",
  "clawdbrain browser pdf",
];
